//
//  Constants.swift
//  BlueChat
//
//  Created by Korisnik on 11/04/2019.
//  Copyright © 2019 Josip Rezic. All rights reserved.
//

import Foundation

struct Constants {
    struct BluetoothService {
        static let bluetoothServiceUUID = "D391A2A2-894D-4264-8B21-87D33F76B8C8" // generated by uuidgen
        static let bluetoothWriteChatacteristicsUUID = "2C6FAC6E-E353-4AAF-87B9-E37AB409AF17" // generated by uuidgen
    }
}
