//
//  DiscoverViewController.swift
//  BlueChat
//
//  Created by Korisnik on 11/04/2019.
//  Copyright © 2019 Josip Rezic. All rights reserved.
//

import UIKit
import CoreBluetooth

class DiscoverViewController: UIViewController {
    
    //
    // MARK: - Variables
    //
    
    private final var centralManager: CBCentralManager?
    private final var peripheralManager: CBPeripheralManager?
    private final var peripherals: [CBPeripheral] = []
    private final var serviceUUID: CBUUID = CBUUID(string: "D391A2A2-894D-4264-8B21-87D33F76B8C8") // generated by uuidgen
    private final let tableView = UITableView()
    
    //
    // MARK: - View methods
    //
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        centralManager = CBCentralManager(delegate: self, queue: .main)
        peripheralManager = CBPeripheralManager(delegate: self, queue: nil)
        
        tableView.frame = view.frame
        view.addSubview(tableView)
        tableView.delegate = self
        tableView.dataSource = self
    }
    
    //
    // MARK: - Methods
    //
    
    private final func startScan() {
        debugPrint("Start scanning...")
        peripherals = []
        centralManager?.scanForPeripherals(withServices: [serviceUUID], options: nil)
    }
}

//
// MARK: - Extension - CBCentralManagerDelegate
//

extension DiscoverViewController: CBCentralManagerDelegate {
    func centralManagerDidUpdateState(_ central: CBCentralManager) {
        debugPrint("centralManagerDidUpdateState:")
        switch central.state {
        case .unknown:
            debugPrint(".unknown")
        case .resetting:
            debugPrint(".resetting")
        case .unsupported:
            debugPrint(".unsupported")
        case .unauthorized:
            debugPrint(".unauthorized")
        case .poweredOff:
            debugPrint(".poweredOff")
        case .poweredOn:
            debugPrint(".poweredOn")
            startScan()
        @unknown default:
            debugPrint(".default")
        }
    }
    
    func centralManager(_ central: CBCentralManager, didDiscover peripheral: CBPeripheral, advertisementData: [String : Any], rssi RSSI: NSNumber) {
        debugPrint("didDiscover peripheral: \(peripheral.name)")
        debugPrint("RSSI: \(RSSI.intValue)")
        peripherals.append(peripheral)
        tableView.reloadData()
        if peripheral != nil {
            /*print("**********************************")
            print("Found new pheripheral devices with services")
            print("Peripheral name: \(String(describing: peripheral.name))")
            print ("Advertisement Data : \(advertisementData)")
            print("ID: \(peripheral.identifier)")
            print("**********************************")
        */}
    }
    
    func centralManager(_ central: CBCentralManager, didConnect peripheral: CBPeripheral) {
        peripheral.delegate = self
        peripheral.discoverServices(nil)
        
//        let messageText = "Poruka text text texttttttt"
//        guard let data = messageText.data(using: .utf8) else {print("aaaaaa"); return}
//        peripheral.writeValue(data, for: characteristic, type: CBCharacteristicWriteType.withResponse)
    }
}

//
// MARK: - Extension - CBPeripheralManagerDelegate
//

extension DiscoverViewController: CBPeripheralManagerDelegate {
    func peripheralManagerDidUpdateState(_ peripheral: CBPeripheralManager) {
        debugPrint("peripheralManagerDidUpdateState:")
        switch peripheral.state {
        case .unknown:
            debugPrint("unknown")
        case .resetting:
            debugPrint("resetting")
        case .unsupported:
            debugPrint("unsupported")
        case .unauthorized:
            debugPrint("unauthorized")
        case .poweredOff:
            debugPrint("poweredOff")
        case .poweredOn:
            debugPrint("poweredOn")
            //let advertisementData = String(format: "%@|%d|%d", "userData.name", "userData.avatarId", "userData.colorId")
            
            
            
            let serialService = CBMutableService(type: serviceUUID, primary: true)
            
            let WR_UUID = CBUUID(string: "2C6FAC6E-E353-4AAF-87B9-E37AB409AF17")
            let WR_PROPERTIES: CBCharacteristicProperties = .write
            let WR_PERMISSIONS: CBAttributePermissions = .writeable
            let writeCharacteristics = CBMutableCharacteristic(type: WR_UUID, properties: WR_PROPERTIES, value: nil, permissions: WR_PERMISSIONS)
            serialService.characteristics = [writeCharacteristics]
            peripheralManager?.add(serialService)
            peripheralManager?.startAdvertising([CBAdvertisementDataServiceUUIDsKey:[serviceUUID], CBAdvertisementDataLocalNameKey: "Jopara"])
        @unknown default:
            debugPrint("default")
        }
    }
    
    func peripheralManager(_ peripheral: CBPeripheralManager, didReceiveWrite requests: [CBATTRequest]) {
        print("didReceiveWrite requests")
        for request in requests {
            if let value = request.value {
                let messageText = String(data: value, encoding: String.Encoding.utf8) as! String
                debugPrint("message text: \(messageText)")
                self.peripheralManager?.respond(to: request, withResult: .success)
            }
        }
    }
}

extension DiscoverViewController: CBPeripheralDelegate {
    func peripheral(_ peripheral: CBPeripheral, didDiscoverServices error: Error?) {
        for service in peripheral.services! {
            peripheral.discoverCharacteristics(nil, for: service)
        }
    }
    
    func peripheral(_ peripheral: CBPeripheral, didDiscoverCharacteristicsFor service: CBService, error: Error?) {
        for characteristic in service.characteristics! {
            let characteristic = characteristic as CBCharacteristic
            print("current UUID: \(characteristic.uuid.uuidString)")
            if characteristic.uuid.uuidString.isEqual("2C6FAC6E-E353-4AAF-87B9-E37AB409AF17") {
                let messageText = "Test message"
                guard let data = messageText.data(using: .utf8) else {print("aaaaaa"); return}
                peripheral.writeValue(data, for: characteristic, type: CBCharacteristicWriteType.withResponse)
            }
        }
    }
}

extension DiscoverViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return peripherals.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = UITableViewCell()
        cell.textLabel?.text = peripherals[indexPath.row].name ?? "Device"
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        centralManager?.connect(peripherals[indexPath.row], options: nil)
    }
}


